# Generated by Django 3.1.4 on 2021-07-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='status',
        ),
    ]
